### ISSUE TITLE
Investigate WebRTC transport

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#102]
This issue is a placeholder so we have an issue number to create a branch.

@jvdrhoof and @jackjansen will do some experiments to see how we can integrate webrtc as an alternative to socketio/dash/tcp transport.

**Comment by jackjansen** [comment]
First success. @jvdrhoof has created a Unity project that uses webRTC to transfer webcam streams between two instances.

The Unity project and the webrtc reflector will be put into GitHub repositories and the URLs will be added here.

We continue in July.

**Comment by jvdrhoof** [comment]
Repository available at https://github.com/jvdrhoof/MyWebRTCPlayer

**Comment by jackjansen** [comment]
Making a lot of progress tonight. Some notes that we shouldn't forget:

- [ ] WebRTCSFU should get a `--verbose` flag (for normal use: print log output for important events) and a `--debug` flag (print everything about everything)
- [ ] GoWebRTCPeer should get a `--verbose` flag (for normal use: print log output for important events) and a `--debug` flag (print everything about everything)
- [ ] All log messages should be structured (`Program: Module: Opened connection to blablablabla`)
- [ ] GoWebRTCPeer should be renamed to WebRTCPeer. Maybe all three repos should get a prefix. @jvdrhoof to decide.
- [ ] All three repos should build with CMake.
- [ ] All three repos should use Github actions to build their stuff (and ideally do some limited testing too).
- [ ] All three repos should get a naming convention where built products are stored, and how they are named.

**Comment by jackjansen** [comment]
- [ ] WebRTCSFU needs an `index.html` that doesn't exist.
- [ ] VR2Gather now gets a URL of some form for webrtc sessions. I think it is in the same place where the Dash URL is, but we need to check to format, and we need to run `GoWebRTCPeer` with that URL as a parameter.

**Comment by jackjansen** [comment]
- [ ] Need to add code to AsyncWebRTCWriter (and maybe reader) to check health of peer.
- [ ] Need to kill peer when object disposed.

**Comment by jackjansen** [comment]
- [ ] Need to look at loading and unloading of the DLL.

**Comment by jackjansen** [comment]
This issue has been superseded by #166
