### ISSUE TITLE
Setting self-representation can crash with "Unknown URL"

### ISSUE THREAD

**Issue by cwidisgroup** [cwi-dis/VR2Gather#103]
Happens for example when starting a built Mediascape, then getting out of the session starting, then trying to change your representaition.

There's apparently something left somewhere that tries to create a TCP connection.

**Comment by jackjansen** [comment]
I have the feeling that this was related to the problem that the transmitter was not disabled in the LoginManager scene, fixed in bf2fa812

**Comment by jackjansen** [comment]
Presumed fixed.
