### ISSUE TITLE
NegateProcessor initialisation still not right

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#104]
There is still an issue with the `NegateProcessor` initialisation.
In mediascape this show by sometimes getting the dialog about the null reference.
It's clearer when building for Android: there you always get an error at startup.

I _think_ the issue is with the order `Awake()` is called for the objects in the scenes: if the VRTInitializer one is called first everything is fine (because it loads the NegateProcessor singleton), but if the _"whatever object it is that parses the input actions"_ one is called first we have the problem.

**Comment by jackjansen** [comment]
This issue may be related (but I'm not sure): https://forum.unity.com/threads/new-input-system-processors-not-appearing-always.911015/

**Comment by jackjansen** [comment]
Hmm. And there may also be an issue in that the `NegateProcessor` factory function is only defined in the editor...

**Comment by jackjansen** [comment]
It turns out the NegateProcessor wasn't involved, probably: it is now gone but the problem persists.

We should debug this on @ashutosh3308 's laptop: it shows the problem most often (2 out of 3 runs, even in the login manager).

It _seems_ that if we disable `P_Self_Login` and only enable it after playback has started we don't see the problem.

The problem is most likely in the initialisation order, with some part _A_ of the event system being initialised either before or after part _B_, and that order determining whether it works or fails.

We should enable full stack traces, that should show us _how_ we get to the problem spot.

We could then look at Project Settings -> Script Execution Order and see if we can somehow influence the order.

**Comment by jackjansen** [comment]
We should also check whether the (outdated, disabled) `InputSystemUIInputModule` have any influence (i.e. does the problem disappear for @ashutosh3308 when we remove them).

We could also temporarily put log statements into `Awake` and `OnEnable` of the `InputSystem` and `XRUIInputModule` classes.

**Comment by jackjansen** [comment]
Putting prints in there doesn't work: the files are somehow overwritten?

But I put breakpoints in the relevant `OnEnable()` methods, and on my machine (where things work fine) the order is

- XRUIInputModule
- XRInteractionManager
- InputActionManager
- EventSystem
- XROrigin
- PlayerControllerSelf.Awake
- PlayerControllerSelf.OnEnable
- PlayerControllerSelf.Start

**Comment by ashutosh3308** [comment]
Repeating on Ashu's machine.

First finding is that the order (above) there is the same, but we do get the exception.

Added a breakpoint to `XRBaseController.OnEnable()`.

Notice that this triggers _very_ early (at least for some comtrollers).

**Comment by jackjansen** [comment]
It appears that there's another way to get this problem, and it is probably the main reason we're sometimes seeing this problem in Mediascape.

When we enable the exception breakpoint at the place stated above (in ApplyProcessors) the stack shows we're coming from `ActionBasedContinuousMoveProvider.ReadInput()`, trying to read the value of the `m_LeftHandMoveAction`.

The game object involved is `Player/Locomotion System/Move Turn VR Controllers`.

**Comment by cwidisgroup** [comment]
For completeness: the commit above (non-reference actions) is what causes the problem. Possibly having something to do with the way we switch scenes.
