### ISSUE TITLE
Upgrade to Unity 2022 LTS

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#128]
This should be quite a bit more painless than the update from 2019 to 2022 (at which time we had to rewrite the complete input system and the VR system).

Checking https://docs.unity3d.com/Manual/UpgradeGuide2022LTS.html it may well be that this is a no-brainer.

The advantage of going to 2022 is that we get access to Netcode. It also seems rumoured that 2022 is the version that will get support for the Apple Vision, and it may be that this will also imply VR on MacOS, we will see.

**Comment by jackjansen** [comment]
This has suddenly become urgent, because for Transmixr Cultural Heritage use case we are going to need this.

@ashutosh3308 I'm going to assign to you for now, just to do the initial testing to see whether it "just works". I've already created the branch.

**Comment by ashutosh3308** [comment]
I upgraded the project to Unity 2022.3 and resolved some errors. I tested solo playground on my laptop and it works fine now.

**Comment by jackjansen** [comment]
Great!
We should try a couple of things tomorrow, with the two of us. Let me see:
- [ ] Creating sessions works
- [ ] Pick up/press button/etc work multi-user
- [ ] movement is seen by others
- [ ] pointclouds work

Thinking about it: maybe we should just merge into Mediascape and run through the experience.
