### ISSUE TITLE
Issues with the LoginManager

### ISSUE THREAD

**Issue by troeggla** [cwi-dis/VR2Gather#129]
- LoginManager does not remember usernames
- When goes through settings dialog, self representation always resets to point cloud

**Comment by jackjansen** [comment]
Confirmed that on `master` I also see the problem of the resetting self-representation to pointcloud.

With "not remembering usernames" the situation may be more subtle: we get into a problem if `autoLogin` is set in `config.json` and the username is empty. Will see if fixing that will also magically fix the not-remembering issue.

**Comment by jackjansen** [comment]
Confirmed fixed.
