### ISSUE TITLE
Schuffling the multiple scenes when created under the new branch `develop/MyNewExperience`

### ISSUE THREAD

**Issue by ashutosh3308** [cwi-dis/VR2Gather#138]
If I have multiple unity `scenes` (Scene1.unity, Scene2.unity) under the new branch `MyNewExperience`. How do you make sure which `scene` is presented first?

I guess, `PilotRegistry.cs` does not exist anymore.

**Comment by jackjansen** [comment]
@ashutosh3308 please check that the documentation update is clear enough and close of so.
