### ISSUE TITLE
Not all participants can hear each other

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#155]
Possibly related to #144 and #141, possibly not.

Since the change to package-based not all voice audio gets through. Some participants can hear some other participants, some not.

Creating this issue mainly so the we have a place to keep notes on what we have found out so far.

**Comment by jackjansen** [comment]
We have tested two-user sessions, both with `socketio` and `tcp` transport.

The session creator can hear the session joiner.

The session joiner cannot hear the session creator.

(@ashutosh3308 is that correct?)

**Comment by ashutosh3308** [comment]
@jackjansen: Yes, it is correct.

**Comment by jackjansen** [comment]
Did a couple of sessions between Mac and Windows, both with TCP transport and SocketIO transport. With Pointclouds and with Avatars.

All the same result: the creator can hear the joiner, the joiner cannot hear the creator.

So it's not a Windows issue, it's not a transport protocol issue.

**Comment by jackjansen** [comment]
Got a little bit further. Found that audio data _is_ transmitted and received correctly. But on the systems where we don't hear anything we are not getting that `stats:` output lines from the `AsyncVoiceDecoder`, so apparently it isn't decoding.

We also see that the `AsyncTCPReader` is dropping all the packets it is receiving (fps=50, fps_dropped=50).

**Comment by jackjansen** [comment]
Oh yes: I think all of this suggests that the problem also isn't with the orchestrator.

**Comment by jackjansen** [comment]
Tried uncompressed audio over TCP: makes no difference, still one-way audio only.
Interestingly, with uncompressed audio we _don't_ get `AsyncTCPReader` stats messages any more.

That evidence points to the `AsyncVoicePreparer`. It doesn't seem to be doing anything on the machine where we don't have audio. And the queue going _into_ to `AsyncVoicePreparer` is blocking. So it is either blocking the `AsyncVoiceDecoder` (causing to `AsyncTCPReader` to drop all its packets to the decoder queue, which does drop) or the `AsyncTCPReader`.

So the question is now: why doesn't the AsyncVoicePreparer do any preparing?

**Comment by jackjansen** [comment]
Next piece of the puzzle: `VoiceReceiver.OnAudioFilterRead()` should be called regularly, and it will get the data from `AsyncVoicePreparer`. It's never called in the "troublesome cases", i.e. on the machines where we don't hear the audio from the other participant.

**Comment by jackjansen** [comment]
Checking the components in `Player.Voice` for the "other player" I see that the working one has a VU meter in its `VoiceReceiver` component (which indeed follows the audio level that's coming out of the speakers). The non-working one doesn't have this.

The `Voice` GameObject starts out empty, and then we programmatically add the `VoiceReceiver` component, which then programmatically adds the `AudioSource` component.

**Comment by jackjansen** [comment]
Ok found the fix. In `VoiceReceiver.Update()` we check that the `AudioSource` is playing, and if it isn't we restart it.

I'm unsure why it stops playing, and why only in some cases, but maybe this has something to with with the creation order of things? Moving the `AudioSource.Start()` from `VoiceReceiver.Init()` to `VoiceReceiver.Start()` might be a good idea...
