### ISSUE TITLE
We need a transport protocol that uses raw TCP to an SFU

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#168]
This is basically the same issue as https://github.com/cwi-dis/vr2gather-orchestrator-v2/issues/18 but on the VR2Gather side.

We need this to be able to replace BestHTTP by another socketio implementation, because only BestHTTP can handle the large packet sizes that are needed for media transport.

**Comment by jackjansen** [comment]
Depends on #150

**Comment by jackjansen** [comment]
Two things seem to be causing issues:

- [ ] The `segmentSize` and `segmentLife` arguments to the dash writers.
- [ ] The funky usage of ports in tcp.

**Comment by ireneviola** [comment]
If issue #169 is completed, this does not need to be finished by June 3rd
