### ISSUE TITLE
Ensure VR2Gather still works on Linux

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#171]
We haven't tried running on Linux for a long time. We should test this.

**Comment by jackjansen** [comment]
And we should also take Linux into account for #170

**Comment by ireneviola** [comment]
For the milestone, it is not necessary, it's a nice-to-have

**Comment by troeggla** [comment]
We will require the reviewers use Windows for the review.
I'm closing this as `wontfix` for now, to be reinvestigated later.
