### ISSUE TITLE
TCPreflector reader statistics are missing

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#189]
This issue is mainly a placeholder for https://github.com/jvdrhoof/mmsys_2025/issues/18 and https://github.com/jvdrhoof/mmsys_2025/issues/17

**Comment by jackjansen** [comment]
Interesting: I cannot repeat this problem on the `master` branch...

**Comment by jvdrhoof** [comment]
Could you try the same with the `166-webrtc` branch?

**Comment by jackjansen** [comment]
I also don't see the problem there. Hunting further.

**Comment by jackjansen** [comment]
Duh. I was climbing up the wrong tree: I was looking for the `AsyncTCPReflectorWriter` stats but these are fine. It's the reader stats that are missing.

**Comment by jackjansen** [comment]
Problem confirmed.
