### ISSUE TITLE
Position tracker file management

### ISSUE THREAD

**Issue by KarolinaWylezek** [cwi-dis/VR2Gather#191]
While switching scenes the previous tracking file gets overwritten.  It is a problem for people having more than one scene, as they cannot collect the tracking information for neither but the last scene. 
It would be good to add a timestamo to file name to prevent that. Adding name of scene would be also helpful for organization purposes. 
Note by Jack: look at how the stats output file is handled.

**Comment by jackjansen** [comment]
PositionTracker settings (including interval) are now overridable from `config.json`, and the output filename can include strings `{scene}` and `{time}` which will be replaced by the scene name and a datetimestamp.
