### ISSUE TITLE
Traction: Failure to restart OpenXRLoader after shutdown.

### ISSUE THREAD

**Issue by nachoreimat** [cwi-dis/VR2Gather#44]
On branch `development/traction` when we switch from the `Cinema` scene to the `TractionLobby` scene it starts popping up an errorLog saying:
`Failure to restart OpenXRLoader after shutdown.
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
`
This is error is thrown by OpenXRRestarter.cs `RestartCoroutine` function line 186.

**Comment by jackjansen** [comment]
Fixed at some point in the past.
