### ISSUE TITLE
Changes needed to pilots when #43 is merged

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#49]
I need to record somewhere what needs to be done to all pilots once we merge #43

One thing I found out: it is good to convert all complex objects (anything that is more than a simple button or a simple grabbable, and even simple grabbables if they need to have a specific orientation when the user is grabbing them) to prefabs. Only then start on the steps below. And test each prefab in isolation by putting an instance in `SoloPlayground` and testing that the interaction works fine.

- [x] Fix `P_Player_xxxx` and `P_Self_player_xxxx`. Best is to have a prefab `P_extras_xxxx`, (re)create variants of `P_Player` and `P_Self_Player`, add the extras prefab, make all the connections and finally put the self/player prefabs into the controller.
   - [ ] Do this by adding the new functionality (as a prefab) to `P_Player`, but disabled. Then, in the scene, the controller has a `Prefabs` child with references to the prefabs. Here re-enable the new functionality.
- [ ] Teleport destinations need to be fixed: See Pilot0 `floor` for example.
   - [ ] Copy component `Teleportation Area` onto floor
   - [ ] Copy collider onto floor (if it doesn't have a collider yet).
- [ ] Grabbable objects need to be fixed, see `PFB_Pilot0ButtonObject` for example:
   - [ ] Layer must be `GrabbableObject`
   - [ ] If transform has rotation `0,0,0` it will probably look good when grabbed with either direct grab or ray-based grab.
   - [ ] Must have a `Rigidbody` and a `Collider` with `Trigger=false`
   - [ ] `Grabbable` with a reference to the `Rigidbody` above.
   - [ ] `XRGrabInteractable` with:
      - [ ] `null` interaction manager (will be set correctly at runtime by FixInteractables) 
      - [ ] Interaction layer mask `Grabbable`
      - [ ] Colliders pointing to the collider above
      - [ ] Interactable event for `SelectEntered` pointing to `Grabbable.OnGrab`
      - [ ] Interactable event for `SelectExited` pointing to `Grabbable.OnRelease`
   - [ ] _Note:_ It may be a good idea to put a subobject `Attach Transform` into the object, and reference that in the `XRGrabInteractable`. That will determine how the object sits in your hand.
- [ ] If there are object factories you should open the scene to ensure the ObjectIDs are generated correctly.
- [ ] Touchable objects need to be fixed, see `PFB_Button` for example:
   - [ ] Layer must be `TouchableObject`
   - [ ] Must have a collider with `trigger=true` (and therefore a `Rigidbody`, but I think it may be on the parent)
   - [ ] `NetworkTrigger` with OnTrigger pointing to a method that does the business-logic action.
   - [ ] `Trigger` (will find `NetworkTrigger` automatically if on the same GameObject)
   - [ ] `XRSimpleInteractable` with:
      - [ ] Interaction Layer Mask `Pointable`
      - [ ] Colliders pointing to the collider on this GameObject
      - [ ] Interactable Event for `Activated` pointing to `Trigger.OnTrigger`.
- [ ] all scenes: `EventSystem` needs to be fixed, see `SoloPlayground` or `LoginManager` for example.
- [ ] all scenes: `SceneController` needs to be adapted. See `Pilot0Controller`.
   - [ ] Allow direct interaction, start faded out
- [ ] all scenes: `VRConfig` is gone.

Some things are going to be more work:

- [] Device-dependent help (such as the billboards in Mediascape). We probably need to create an example for that.
- [] Actually, we may also want an example for a UI. LoginManager is one, but it's rather convoluted.
- [] Objects created on the fly (such as the Mediascape photographs) need to be implemented smartly. I think the best way is to have an `GrabbableFactory` with an Orchestrator API which does the actual creation on the master (inventing the UUID there) and then broadcasting the creation message. Shouldn't be too difficult with careful use of prefabs.

**Comment by cwidisgroup** [comment]
Traction: disabling hands isn't implemented (in PlayerCOntrollerBase).

**Comment by jackjansen** [comment]
All production branches are now up-to-date so this can be closed.
