### ISSUE TITLE
Create prefabs for all object shared between instances

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/VR2Gather#71]
That's going to be:

- [ ] Buttons
- [ ] Grabbables
- [ ] Creatable-grabbables
- [ ] non-grabbable solid bodies

We then need to use these prefabs on all objects in

- [ ] main branch
- [ ] Mediascape
- [ ] Traction
- [ ] Transmixr

I'm reasonably sure the other deployment scenarios (medical, cake) don't need this.

**Comment by cwidisgroup** [comment]
Direct interactions with buttons seems to be sticky. I've attached a video to better explain the problem

https://user-images.githubusercontent.com/26714744/224765230-6566b96a-57c7-4fb0-8594-e547bb570beb.mp4

**Comment by jackjansen** [comment]
All fixed, at some time in the past.
