### ISSUE TITLE
Mannequin and mediascape costume size should be adapted for user

### ISSUE THREAD

**Issue by cwidisgroup** [cwi-dis/VR2Gather#87]
I have some ideas on how to do this (when doing the "reset view") with the new rigging stuff. Basically by adding a UnityEvent there that will happen when you press reset, by taking the height of the HMD from the floor, multiplying by a given factor and using that to modify the scale of the costume.

**Comment by jackjansen** [comment]
The sizing seems to work. The branch is now used for fixing the costume animation.
There's now code that tries to keep the feet above the ground, and if you move your head down it will bend the costume knees. It seems to start working.

We started with the Valem video tutorials, but that was mainly for use in animation, so came up with something ourselves (mainly based on colliders to keep the feet from sinking into the floor).

@shirsub also found this video that may be interesting: https://www.youtube.com/watch?v=tgacoq7qhEo
